### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys-Backend#1]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/FranprzDev/EduSys-Backend/assets/53904695/9b26cc5b-ab30-49dc-a382-e242eeddab54)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FranprzDev** [comment]
Hola nico, cómo estás? Debo eliminar TODOS los comentarios que están en el backend?
¿Esa es la única correción? ¿Debo crear una rama llamada 'bugFix' y luego tengo que ponerlo de vuelta en la rama de main para deployar de vuelta el proyecto?

**Comment by Nidev-lab** [comment]
Hola buenas! No, solo borra los comentarios y subi los cambios a la rama principal del repo.

**Comment by FranprzDev** [comment]
Hola Nico, ya está corregido este error.
